// FILE MEMO: Public exports for @filepad/agent-access-sdk.

export { FilepadAgentClient } from './client.js';
export { FilepadAgentHttpClient } from './endpoints.js';
export { McpAdapter } from './mcp.js';
export { signRequest, buildCanonicalString, serializeBody, sha256Hex } from './auth.js';
export {
  FilepadAgentError,
  AuthenticationError,
  ForbiddenScopeError,
  NotFoundError,
  ConflictError,
  RateLimitError,
  ProposalPathError,
  BaseTextMismatchError,
  StaleVersionError,
  InvalidRequestError,
  fromResponse,
} from './errors.js';

export type {
  FilepadAgentClientConfig,
  SignedRequest,
  AgentAccessScope,
  AgentArtifactKind,
  AgentCreateArtifactKind,
  AgentConnectDiagnosticsResponse,
  AgentToolQuickReference,
  AgentConnectScopeStatus,
  AgentApiPrompt,
  AgentApiSearchMode,
  AgentApiSearchResult,
  CreateAgentApiArtifactRequest,
  CreateAgentApiArtifactResponse,
  CreateAgentApiEventRequest,
  CreateAgentApiEventResponse,
  CreateAgentApiSignalRequest,
  CreateAgentApiSignalResponse,
  AckAgentMailboxResponse,
  AgentProfile,
  AgentProfileField,
  AgentProfileFile,
  AgentMailboxItem,
  AgentMailboxItemKind,
  AgentSignal,
  AgentSignalSeverity,
  AgentSignalStatus,
  GetAgentApiCapabilitiesResponse,
  GetAgentApiEnvironmentResponse,
  GetAgentApiFileResponse,
  GetAgentApiFileTreeResponse,
  GetAgentApiPromptsResponse,
  ListAgentMailboxResponse,
  ListAgentSignalsResponse,
  GetMcpPromptsResponse,
  GetMcpResourcesResponse,
  AgentRuntimeTool,
  ListAgentToolsResponse,
  CallAgentToolRequest,
  CallAgentToolResponse,
  CreateContractRequest,
  CreateContractResponse,
  GetContractStatusRequest,
  GetContractStatusResponse,
  GmailDraftToolInput,
  GmailGetMessageToolInput,
  GmailImportMessageToolInput,
  GmailSearchToolInput,
  McpPrompt,
  McpResource,
  SearchAgentApiWorkspaceRequest,
  SearchAgentApiWorkspaceResponse,
  UpdateAgentProfileRequest,
  UpdateAgentProfileResponse,
  GetConstitutionResponse,
  WorkspaceConstitution,
  ConstitutionTerritory,
  ConstitutionActiveContext,
  ConstitutionActiveContextPendingItem,
  ConstitutionBehavioralRule,
  ConstitutionCommunication,
  ConstitutionVocabularyEntry,
} from './types.js';
